packages:
  - 'apps/desktop'
  - 'apps/web'
  - 'packages/*'
  - 'services/api'
  - 'tools/*'

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true

engineStrict: true
pmOnFail: download
