package com.databreeze.android.network

import com.databreeze.android.security.AndroidDeviceSigningKeyStore
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import java.security.MessageDigest
import java.time.Instant
import java.util.UUID

/** Typed device enrollment client. Proof-of-possession is generated by Android Keystore only. */
class DeviceEnrollmentApiClient(
    private val transport: AuthenticatedApiTransport,
    private val signingKeys: AndroidDeviceSigningKeyStore,
    private val installationIdHash: String,
    private val now: () -> Instant = { Instant.now() },
) {
    sealed interface Result {
        data class Enrolled(val deviceId: String) : Result
        data class Rejected(val code: String) : Result
        data object Retryable : Result
    }

    suspend fun enroll(): Result {
        if (!installationIdHash.matches(DIGEST)) return Result.Rejected("installation_identity_invalid")
        val challengeId = UUID.randomUUID().toString()
        val issued = now()
        val expires = issued.plusSeconds(5 * 60)
        val digest = sha256("$challengeId\u0000$installationIdHash\u0000${issued}\u0000${expires}".toByteArray())
        val keyHandle = runCatching { signingKeys.getOrCreate("device-signing") }.getOrElse {
            return Result.Rejected("ed25519_keystore_unavailable")
        }
        val challengeBody = mapper.writeValueAsString(
            linkedMapOf(
                "challengeId" to challengeId,
                "platform" to "ANDROID",
                "installationIdHash" to installationIdHash,
                "challengeDigest" to digest,
                "issuedAt" to issued.toString(),
                "expiresAt" to expires.toString(),
            ),
        )
        val challenge = transport.execute(
            AuthenticatedHttpRequest("POST", "/v1/devices/enrollment-challenges", challengeBody, "device-challenge-$challengeId"),
        )
        when (challenge) {
            is AuthenticatedHttpResult.TerminalAuthFailure -> return Result.Rejected("device_enrollment_auth_denied")
            is AuthenticatedHttpResult.RetryableFailure,
            is AuthenticatedHttpResult.NetworkFailure,
            -> return Result.Retryable
            is AuthenticatedHttpResult.Success -> Unit
        }
        val challengeValue = runCatching { mapper.readTree((challenge as AuthenticatedHttpResult.Success).body).get("value") }.getOrNull()
        if (challengeValue?.text("id") != challengeId) return Result.Rejected("device_challenge_invalid")
        val deviceId = UUID.randomUUID().toString()
        val proof = runCatching { signingKeys.sign(keyHandle, digest.toByteArray(Charsets.UTF_8)) }.getOrElse {
            return Result.Rejected("device_proof_unavailable")
        }
        val enrollBody = mapper.writeValueAsString(
            linkedMapOf(
                "challengeId" to challengeId,
                "deviceId" to deviceId,
                "publicKey" to signingKeys.publicKeyBase64(keyHandle),
                "proof" to proof,
                "now" to now().toString(),
            ),
        )
        return when (val result = transport.execute(AuthenticatedHttpRequest("POST", "/v1/devices/enroll", enrollBody, "device-enroll-$deviceId"))) {
            is AuthenticatedHttpResult.Success -> {
                val value = runCatching { mapper.readTree(result.body).get("value") }.getOrNull()
                if (value?.text("id") == deviceId) Result.Enrolled(deviceId)
                else Result.Rejected("device_enrollment_response_invalid")
            }
            is AuthenticatedHttpResult.TerminalAuthFailure -> Result.Rejected("device_enrollment_auth_denied")
            is AuthenticatedHttpResult.RetryableFailure,
            is AuthenticatedHttpResult.NetworkFailure,
            -> Result.Retryable
        }
    }

    private fun sha256(bytes: ByteArray): String = MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

    private companion object {
        val DIGEST = Regex("^[a-f0-9]{64}$")
        val mapper = jacksonObjectMapper()
        fun JsonNode.text(key: String): String? = get(key)?.takeIf { it.isTextual }?.textValue()
    }
}
