import assert from 'node:assert/strict';
import {
  appendFileSync,
  cpSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const generatorPath = resolve(packageRoot, 'scripts/generate-models.mjs');
const fixtureRoot = resolve(packageRoot, 'test/fixtures/generator');
const generatedRoot = resolve(packageRoot, 'generated');
const expectedFiles = [
  'kotlin/src/main/kotlin/com/databreeze/contracts/v1/Models.kt',
  'kotlin/src/main/kotlin/com/databreeze/contracts/v1/Validation.kt',
  'python/databreeze_contracts/__init__.py',
  'python/databreeze_contracts/py.typed',
  'python/databreeze_contracts/v1/__init__.py',
  'python/databreeze_contracts/v1/_validation.py',
  'python/databreeze_contracts/v1/models.py',
  'python/pyproject.toml',
  'typescript/v1/index.ts',
  'typescript/v1/validation.mjs',
];

function runGenerator(...args) {
  return spawnSync(process.execPath, [generatorPath, ...args], {
    cwd: packageRoot,
    encoding: 'utf8',
  });
}

function listFiles(root, directory = root) {
  if (!existsSync(directory)) return [];

  return readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const path = join(directory, entry.name);
      return entry.isDirectory()
        ? listFiles(root, path)
        : [relative(root, path).replaceAll('\\', '/')];
    })
    .sort();
}

function snapshot(root) {
  return listFiles(root).map((path) => [
    path,
    readFileSync(resolve(root, path)).toString('base64'),
  ]);
}

function withTemporaryDirectory(run) {
  const directory = mkdtempSync(join(tmpdir(), 'databreeze-contracts-test-'));
  try {
    return run(directory);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

function runPythonValidationProgram(program) {
  const source = resolve(generatedRoot, 'python/databreeze_contracts/v1/_validation.py');
  assert.equal(existsSync(source), true, 'generated Python validation helpers are missing');
  return spawnSync('python', ['-c', program, source], {
    cwd: packageRoot,
    encoding: 'utf8',
  });
}

test('generates byte-stable language packages from a controlled registry', () => {
  withTemporaryDirectory((directory) => {
    const first = resolve(directory, 'first');
    const second = resolve(directory, 'second');
    const firstRun = runGenerator('--source', fixtureRoot, '--output', first);
    const secondRun = runGenerator('--source', fixtureRoot, '--output', second);

    assert.equal(firstRun.status, 0, firstRun.stderr);
    assert.equal(secondRun.status, 0, secondRun.stderr);
    assert.deepEqual(listFiles(first), expectedFiles);
    assert.deepEqual(snapshot(first), snapshot(second));

    for (const path of expectedFiles.filter((entry) => !entry.endsWith('py.typed'))) {
      const content = readFileSync(resolve(first, path), 'utf8');
      assert.match(content, /^[/#].*Generated by @databreeze\/contracts\. DO NOT EDIT\./);
      assert.equal(content.includes('\r'), false, `${path} must use LF newlines`);
      assert.equal(content.endsWith('\n'), true, `${path} must end with a newline`);
    }

    const typescript = readFileSync(resolve(first, 'typescript/v1/index.ts'), 'utf8');
    assert.match(typescript, /export type Alpha = string;/);
    assert.match(typescript, /export interface SampleEnvelope<TData extends object = JsonObject>/);
    assert.ok(
      typescript.indexOf('export type Alpha') <
        typescript.indexOf('export interface SampleEnvelope'),
    );
    assert.ok(
      typescript.indexOf('readonly data: TData;') < typescript.indexOf('readonly id: Alpha;'),
    );
    assert.match(typescript, /readonly kind: "sample";/);
    assert.match(typescript, /readonly labels\?: readonly string\[\];/);

    const kotlin = readFileSync(
      resolve(first, 'kotlin/src/main/kotlin/com/databreeze/contracts/v1/Models.kt'),
      'utf8',
    );
    assert.match(kotlin, /package com\.databreeze\.contracts\.v1/);
    assert.match(kotlin, /public typealias Alpha = String/);
    assert.match(kotlin, /public data class SampleEnvelope<TData>/);

    const python = readFileSync(resolve(first, 'python/databreeze_contracts/v1/models.py'), 'utf8');
    assert.match(python, /class ClosedModel\(BaseModel\):/);
    assert.match(python, /model_config = ConfigDict\(extra="forbid"\)/);
    assert.match(python, /TData = TypeVar\("TData"\)/);
    assert.match(python, /class SampleEnvelope\(ClosedModel, Generic\[TData\]\):/);

    const check = runGenerator('--check', '--source', fixtureRoot, '--output', first);
    assert.equal(check.status, 0, check.stderr);
    assert.match(check.stdout, /Generated contract files are up to date\./);
  });
});

test('fails loudly when a schema uses an unsupported construct', () => {
  withTemporaryDirectory((directory) => {
    const source = resolve(directory, 'source');
    cpSync(fixtureRoot, source, { recursive: true });
    const schemaPath = resolve(source, 'schemas/v1/alpha.schema.json');
    const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
    schema.enum = ['alpha'];
    writeFileSync(schemaPath, `${JSON.stringify(schema, null, 2)}\n`);

    const result = runGenerator('--source', source, '--output', resolve(directory, 'output'));

    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /Unsupported JSON Schema keyword "enum"/);
    assert.match(result.stderr, /alpha\.schema\.json/);
  });
});

test('fails loudly when a schema contains the unsatisfiable false schema', () => {
  withTemporaryDirectory((directory) => {
    const source = resolve(directory, 'source');
    cpSync(fixtureRoot, source, { recursive: true });
    const schemaPath = resolve(source, 'schemas/v1/sample-envelope.schema.json');
    const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
    schema.properties.labels.items = false;
    writeFileSync(schemaPath, `${JSON.stringify(schema, null, 2)}\n`);

    const result = runGenerator('--source', source, '--output', resolve(directory, 'output'));

    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /Unsupported boolean JSON Schema false/);
    assert.match(result.stderr, /sample-envelope\.schema\.json#\/properties\/labels\/items/);
  });
});

test('drift check reports missing stale and unexpected files without mutation', () => {
  withTemporaryDirectory((directory) => {
    const output = resolve(directory, 'output');
    const generate = runGenerator('--source', fixtureRoot, '--output', output);
    assert.equal(generate.status, 0, generate.stderr);

    const missing = 'kotlin/src/main/kotlin/com/databreeze/contracts/v1/Models.kt';
    const stale = 'typescript/v1/index.ts';
    const unexpected = 'typescript/v1/obsolete.ts';
    unlinkSync(resolve(output, missing));
    appendFileSync(resolve(output, stale), '// stale\n');
    writeFileSync(resolve(output, unexpected), '// unexpected\n');
    const before = snapshot(output);

    const check = runGenerator('--check', '--source', fixtureRoot, '--output', output);

    assert.notEqual(check.status, 0);
    assert.match(check.stderr, new RegExp(`missing: ${missing.replaceAll('/', '\\/')}`));
    assert.match(check.stderr, new RegExp(`stale: ${stale.replaceAll('/', '\\/')}`));
    assert.match(check.stderr, new RegExp(`unexpected: ${unexpected.replaceAll('/', '\\/')}`));
    assert.deepEqual(snapshot(output), before);
  });
});

test('generation refuses to replace its schema source tree', () => {
  withTemporaryDirectory((directory) => {
    const source = resolve(directory, 'source');
    cpSync(fixtureRoot, source, { recursive: true });
    const before = snapshot(source);

    const generate = runGenerator('--source', source, '--output', source);

    assert.notEqual(generate.status, 0);
    assert.match(generate.stderr, /Refusing to replace a source tree with generated output/);
    assert.deepEqual(snapshot(source), before);
  });
});

test('the checked-in TypeScript contracts compile in strict mode', () => {
  const source = resolve(generatedRoot, 'typescript/v1/index.ts');
  assert.equal(existsSync(source), true, 'generated TypeScript entry point is missing');
  withTemporaryDirectory((directory) => {
    let importPath = relative(directory, source).replaceAll('\\', '/').replace(/\.ts$/u, '.js');
    if (!importPath.startsWith('.')) importPath = `./${importPath}`;
    const consumer = resolve(directory, 'consumer.ts');
    writeFileSync(
      consumer,
      [
        `import type { CommandEnvelope, EventEnvelope } from ${JSON.stringify(importPath)};`,
        '',
        'interface DomainPayload {',
        '  readonly displayName: string;',
        '}',
        '',
        'declare const command: CommandEnvelope<DomainPayload>;',
        'declare const event: EventEnvelope<DomainPayload>;',
        'const commandName: string = command.data.displayName;',
        'const eventName: string = event.data.displayName;',
        'void commandName;',
        'void eventName;',
        '',
      ].join('\n'),
    );
    const compiler = resolve(packageRoot, '../../node_modules/typescript/bin/tsc');
    const result = spawnSync(
      process.execPath,
      [
        compiler,
        '--noEmit',
        '--strict',
        '--target',
        'ES2024',
        '--module',
        'NodeNext',
        '--moduleResolution',
        'NodeNext',
        '--skipLibCheck',
        consumer,
      ],
      { cwd: packageRoot, encoding: 'utf8' },
    );

    assert.equal(result.status, 0, `${result.error ?? ''}\n${result.stdout}\n${result.stderr}`);
  });
});

test('the checked-in Python package compiles with the available interpreter', () => {
  const files = expectedFiles
    .filter((path) => path.endsWith('.py'))
    .map((path) => resolve(generatedRoot, path));
  for (const path of files) assert.equal(existsSync(path), true, `${path} is missing`);
  const program = [
    'from pathlib import Path',
    'import sys',
    'for name in sys.argv[1:]:',
    '    source = Path(name).read_text(encoding="utf-8")',
    '    compile(source, name, "exec")',
  ].join('\n');
  const result = spawnSync('python', ['-c', program, ...files], {
    cwd: packageRoot,
    encoding: 'utf8',
  });

  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
});

test('generated Pydantic models reject explicit nulls and omit absent properties by default', () => {
  const models = readFileSync(
    resolve(generatedRoot, 'python/databreeze_contracts/v1/models.py'),
    'utf8',
  );
  assert.match(
    models,
    /return reject_explicit_null_properties\(value, frozenset\(cls\.model_fields\)\)/,
  );
  assert.match(
    models,
    /return super\(\)\.model_dump\(\*args, \*\*serialization_options\(kwargs\)\)/,
  );
  assert.match(
    models,
    /return super\(\)\.model_dump_json\(\*args, \*\*serialization_options\(kwargs\)\)/,
  );

  const program = [
    'import json',
    'import runpy',
    'import sys',
    'helpers = runpy.run_path(sys.argv[1])',
    'reject = helpers["reject_explicit_null_properties"]',
    'options = helpers["serialization_options"]',
    'missing = reject({"status": 400}, frozenset({"status", "detail"}))',
    'try:',
    '    reject({"status": 400, "detail": None}, frozenset({"status", "detail"}))',
    '    explicit_null_rejected = False',
    'except ValueError:',
    '    explicit_null_rejected = True',
    'print(json.dumps([missing, explicit_null_rejected, options({}), options({"exclude_unset": False})], sort_keys=True))',
  ].join('\n');
  const result = runPythonValidationProgram(program);

  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
  assert.equal(
    result.stdout.trim(),
    '[{"status": 400}, true, {"exclude_unset": true}, {"exclude_unset": false}]',
  );
});

test('generated Python helpers preserve formats and strict primitive declarations', () => {
  const models = readFileSync(
    resolve(generatedRoot, 'python/databreeze_contracts/v1/models.py'),
    'utf8',
  );
  assert.match(
    models,
    /Identifier: TypeAlias = Annotated\[StrictStr, AfterValidator\(validate_uuid\)\]/,
  );
  assert.match(
    models,
    /UtcTimestamp: TypeAlias = Annotated\[StrictStr, AfterValidator\(validate_utc_timestamp\)\]/,
  );
  assert.match(models, /status: Annotated\[int, Field\(strict=True, ge=100, le=599\)\]/);
  assert.match(models, /retryable: StrictBool/);
  assert.match(models, /type: Annotated\[StrictStr, AfterValidator\(validate_uri_reference\)\]/);
  assert.match(
    models,
    /instance: Annotated\[StrictStr, AfterValidator\(validate_uri_reference\)\] \| None = None/,
  );
  const pyprojectPath = resolve(generatedRoot, 'python/pyproject.toml');
  assert.equal(existsSync(pyprojectPath), true, 'generated Python dependency manifest is missing');
  const pyproject = readFileSync(pyprojectPath, 'utf8');
  assert.match(pyproject, /"pydantic==2\.13\.4"/);
  assert.match(pyproject, /"rfc3339-validator==0\.1\.4"/);
  assert.match(pyproject, /"rfc3986-validator==0\.1\.1"/);

  const helpers = readFileSync(
    resolve(generatedRoot, 'python/databreeze_contracts/v1/_validation.py'),
    'utf8',
  );
  assert.match(helpers, /from uuid import UUID/);
  assert.match(helpers, /from rfc3339_validator import validate_rfc3339/);
  assert.match(helpers, /from rfc3986_validator import validate_rfc3986/);
  assert.match(helpers, /UUID\(candidate\)/);
  assert.match(helpers, /validate_rfc3339\(value\)/);
  assert.match(helpers, /validate_rfc3986\(value, rule="URI_reference"\)/);
  assert.doesNotMatch(helpers, /datetime\.fromisoformat|urlsplit|_UTC_TIMESTAMP|_UUID =/);

  const ajv = new Ajv2020({ strict: true });
  addFormats(ajv);
  const validators = {
    'date-time': ajv.compile({ type: 'string', format: 'date-time', pattern: 'Z$' }),
    'uri-reference': ajv.compile({ type: 'string', format: 'uri-reference' }),
    uuid: ajv.compile({ type: 'string', format: 'uuid' }),
  };
  const cases = [
    ['uri-reference', 'abc]'],
    ['uri-reference', 'http://example.com/[]'],
    ['uri-reference', 'foo#bar#baz'],
    ['date-time', '2016-12-31T23:59:60Z'],
    ['date-time', '2016-12-31T23:60:00Z'],
    ['uuid', 'urn:uuid:018f47f2-5ee1-7d8d-a4c2-8f0e19e4cc01'],
  ];
  assert.deepEqual(
    cases.map(([format, value]) => validators[format](value)),
    [false, false, false, true, false, true],
  );
});

test('generated Pydantic tenant discriminators remain required', () => {
  const models = readFileSync(
    resolve(generatedRoot, 'python/databreeze_contracts/v1/models.py'),
    'utf8',
  );

  assert.match(models, /scopeType: Literal\["organization"\]\n/);
  assert.match(models, /scopeType: Literal\["workspace"\]\n/);
  assert.match(models, /scopeType: Literal\["project"\]\n/);
  assert.doesNotMatch(models, /scopeType: Literal\[[^\]]+\] =/);
});

test('generated Kotlin models preserve cursor and problem constructor invariants', () => {
  const kotlin = readFileSync(
    resolve(generatedRoot, 'kotlin/src/main/kotlin/com/databreeze/contracts/v1/Models.kt'),
    'utf8',
  );

  assert.match(
    kotlin,
    /require\(if \(hasMore\) !nextCursor\.isNullOrEmpty\(\) else nextCursor == null\)/,
  );
  assert.doesNotMatch(kotlin, /nextCursor\.isNullOrBlank\(\)/);
  assert.equal(' '.length >= 1, true, 'JSON Schema minLength: 1 accepts a whitespace cursor');
  assert.match(kotlin, /require\(titleKey != null \|\| messageKey != null\)/);
});

test('the checked-in Kotlin models have a deterministic standard-Kotlin structure', () => {
  const source = resolve(
    generatedRoot,
    'kotlin/src/main/kotlin/com/databreeze/contracts/v1/Models.kt',
  );
  assert.equal(existsSync(source), true, 'generated Kotlin source is missing');
  const kotlin = readFileSync(source, 'utf8');

  assert.match(kotlin, /^\/\/ Generated by @databreeze\/contracts\. DO NOT EDIT\.\n/);
  assert.match(kotlin, /package com\.databreeze\.contracts\.v1/);
  assert.match(kotlin, /public sealed interface TenantScope/);
  assert.match(kotlin, /public data class OrganizationScope/);
  assert.match(kotlin, /public data class WorkspaceScope/);
  assert.match(kotlin, /public data class ProjectScope/);
  assert.match(kotlin, /public data class CommandEnvelope<TData>/);
  assert.match(kotlin, /public data class CursorPage<TItem>/);
  assert.match(kotlin, /public data class EventEnvelope<TData>/);
  assert.doesNotMatch(kotlin, /android\.|androidx\.|kotlinx\./);
  assert.equal((kotlin.match(/\{/g) ?? []).length, (kotlin.match(/\}/g) ?? []).length);
  assert.equal((kotlin.match(/\(/g) ?? []).length, (kotlin.match(/\)/g) ?? []).length);
});
